<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="pt" xml:lang="pt"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.0.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Marcio Vakassugui">

<title>Lista de Exercícios 01 - Curso Modelagem Linear</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
span.underline{text-decoration: underline;}
div.column{display: inline-block; vertical-align: top; width: 50%;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>


<script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="custom_quarto.css">
</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article toc-left">
<div id="quarto-sidebar-toc-left" class="sidebar toc-left">
  <nav id="TOC" role="doc-toc">
    <h2 id="toc-title">Conteúdo</h2>
   
  <ul>
  <li><a href="#dados" id="toc-dados" class="nav-link active" data-scroll-target="#dados">Dados</a>
  <ul class="collapse">
  <li><a href="#variáveis-tipos-e-valores-missing" id="toc-variáveis-tipos-e-valores-missing" class="nav-link" data-scroll-target="#variáveis-tipos-e-valores-missing">Variáveis, tipos e valores missing</a></li>
  <li><a href="#dicionário-de-dados" id="toc-dicionário-de-dados" class="nav-link" data-scroll-target="#dicionário-de-dados">Dicionário de dados</a></li>
  </ul></li>
  <li><a href="#exercício-1" id="toc-exercício-1" class="nav-link" data-scroll-target="#exercício-1">Exercício 1</a></li>
  <li><a href="#exercício-2" id="toc-exercício-2" class="nav-link" data-scroll-target="#exercício-2">Exercício 2</a></li>
  <li><a href="#exercício-3" id="toc-exercício-3" class="nav-link" data-scroll-target="#exercício-3">Exercício 3</a></li>
  <li><a href="#exercício-4" id="toc-exercício-4" class="nav-link" data-scroll-target="#exercício-4">Exercício 4</a></li>
  <li><a href="#exercício-5" id="toc-exercício-5" class="nav-link" data-scroll-target="#exercício-5">Exercício 5</a></li>
  <li><a href="#exercício-6" id="toc-exercício-6" class="nav-link" data-scroll-target="#exercício-6">Exercício 6</a></li>
  <li><a href="#exercício-7" id="toc-exercício-7" class="nav-link" data-scroll-target="#exercício-7">Exercício 7</a></li>
  <li><a href="#exercício-8" id="toc-exercício-8" class="nav-link" data-scroll-target="#exercício-8">Exercício 8</a></li>
  <li><a href="#exercício-9" id="toc-exercício-9" class="nav-link" data-scroll-target="#exercício-9">Exercício 9</a></li>
  <li><a href="#exercício-10" id="toc-exercício-10" class="nav-link" data-scroll-target="#exercício-10">Exercício 10</a></li>
  <li><a href="#análises-complementares" id="toc-análises-complementares" class="nav-link" data-scroll-target="#análises-complementares">Análises Complementares</a></li>
  <li><a href="#conclusão" id="toc-conclusão" class="nav-link" data-scroll-target="#conclusão">Conclusão</a></li>
  </ul>
</nav>
</div>
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
</div>
<main class="content page-columns page-full" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Lista de Exercícios 01 - Curso Modelagem Linear</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Autor:</div>
    <div class="quarto-title-meta-contents">
             <p>Marcio Vakassugui </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Publicaçao:</div>
    <div class="quarto-title-meta-contents">
      <p class="date">29 de agosto de 2022</p>
    </div>
  </div>
    
  </div>
  
<div>
  <div class="abstract">
    <div class="abstract-title">Resumo</div>
    Resolução da lista de exercícios sobre modelagem linear simples e múltipla. Questões de 01 a 10.
  </div>
</div>

</header>

<section id="dados" class="level2">
<h2 class="anchored" data-anchor-id="dados">Dados</h2>
<p class="question">
O banco de dados <code>Boston</code> apresenta registros de valores medianos das casas (<code>medv</code>) de 506 bairros de Boston. O objetivo é identificar quais das 13 variáveis explicativas estão associadas com esses valores e usá-las para fazer predições de preços das casas.
</p>
<section id="variáveis-tipos-e-valores-missing" class="level3">
<h3 class="anchored" data-anchor-id="variáveis-tipos-e-valores-missing">Variáveis, tipos e valores missing</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(MASS<span class="sc">::</span>Boston, <span class="at">n =</span> <span class="dv">5</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     crim zn indus chas   nox    rm  age    dis rad tax ptratio  black lstat
1 0.00632 18  2.31    0 0.538 6.575 65.2 4.0900   1 296    15.3 396.90  4.98
2 0.02731  0  7.07    0 0.469 6.421 78.9 4.9671   2 242    17.8 396.90  9.14
3 0.02729  0  7.07    0 0.469 7.185 61.1 4.9671   2 242    17.8 392.83  4.03
4 0.03237  0  2.18    0 0.458 6.998 45.8 6.0622   3 222    18.7 394.63  2.94
5 0.06905  0  2.18    0 0.458 7.147 54.2 6.0622   3 222    18.7 396.90  5.33
  medv
1 24.0
2 21.6
3 34.7
4 33.4
5 36.2</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>dplyr<span class="sc">::</span><span class="fu">glimpse</span>(MASS<span class="sc">::</span>Boston)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 506
Columns: 14
$ crim    &lt;dbl&gt; 0.00632, 0.02731, 0.02729, 0.03237, 0.06905, 0.02985, 0.08829,…
$ zn      &lt;dbl&gt; 18.0, 0.0, 0.0, 0.0, 0.0, 0.0, 12.5, 12.5, 12.5, 12.5, 12.5, 1…
$ indus   &lt;dbl&gt; 2.31, 7.07, 7.07, 2.18, 2.18, 2.18, 7.87, 7.87, 7.87, 7.87, 7.…
$ chas    &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
$ nox     &lt;dbl&gt; 0.538, 0.469, 0.469, 0.458, 0.458, 0.458, 0.524, 0.524, 0.524,…
$ rm      &lt;dbl&gt; 6.575, 6.421, 7.185, 6.998, 7.147, 6.430, 6.012, 6.172, 5.631,…
$ age     &lt;dbl&gt; 65.2, 78.9, 61.1, 45.8, 54.2, 58.7, 66.6, 96.1, 100.0, 85.9, 9…
$ dis     &lt;dbl&gt; 4.0900, 4.9671, 4.9671, 6.0622, 6.0622, 6.0622, 5.5605, 5.9505…
$ rad     &lt;int&gt; 1, 2, 2, 3, 3, 3, 5, 5, 5, 5, 5, 5, 5, 4, 4, 4, 4, 4, 4, 4, 4,…
$ tax     &lt;dbl&gt; 296, 242, 242, 222, 222, 222, 311, 311, 311, 311, 311, 311, 31…
$ ptratio &lt;dbl&gt; 15.3, 17.8, 17.8, 18.7, 18.7, 18.7, 15.2, 15.2, 15.2, 15.2, 15…
$ black   &lt;dbl&gt; 396.90, 396.90, 392.83, 394.63, 396.90, 394.12, 395.60, 396.90…
$ lstat   &lt;dbl&gt; 4.98, 9.14, 4.03, 2.94, 5.33, 5.21, 12.43, 19.15, 29.93, 17.10…
$ medv    &lt;dbl&gt; 24.0, 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15…</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>skimr<span class="sc">::</span><span class="fu">skim</span>(MASS<span class="sc">::</span>Boston)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped">
<caption>Data summary</caption>
<tbody>
<tr class="odd">
<td style="text-align: left;">Name</td>
<td style="text-align: left;">MASS::Boston</td>
</tr>
<tr class="even">
<td style="text-align: left;">Number of rows</td>
<td style="text-align: left;">506</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Number of columns</td>
<td style="text-align: left;">14</td>
</tr>
<tr class="even">
<td style="text-align: left;">_______________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Column type frequency:</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">numeric</td>
<td style="text-align: left;">14</td>
</tr>
<tr class="odd">
<td style="text-align: left;">________________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Group variables</td>
<td style="text-align: left;">None</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table class="table table-sm table-striped">
<colgroup>
<col style="width: 15%">
<col style="width: 10%">
<col style="width: 15%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 6%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">skim_variable</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: right;">mean</th>
<th style="text-align: right;">sd</th>
<th style="text-align: right;">p0</th>
<th style="text-align: right;">p25</th>
<th style="text-align: right;">p50</th>
<th style="text-align: right;">p75</th>
<th style="text-align: right;">p100</th>
<th style="text-align: left;">hist</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">crim</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3.61</td>
<td style="text-align: right;">8.60</td>
<td style="text-align: right;">0.01</td>
<td style="text-align: right;">0.08</td>
<td style="text-align: right;">0.26</td>
<td style="text-align: right;">3.68</td>
<td style="text-align: right;">88.98</td>
<td style="text-align: left;">▇▁▁▁▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">zn</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">11.36</td>
<td style="text-align: right;">23.32</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">12.50</td>
<td style="text-align: right;">100.00</td>
<td style="text-align: left;">▇▁▁▁▁</td>
</tr>
<tr class="odd">
<td style="text-align: left;">indus</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">11.14</td>
<td style="text-align: right;">6.86</td>
<td style="text-align: right;">0.46</td>
<td style="text-align: right;">5.19</td>
<td style="text-align: right;">9.69</td>
<td style="text-align: right;">18.10</td>
<td style="text-align: right;">27.74</td>
<td style="text-align: left;">▇▆▁▇▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">chas</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.07</td>
<td style="text-align: right;">0.25</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: left;">▇▁▁▁▁</td>
</tr>
<tr class="odd">
<td style="text-align: left;">nox</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.55</td>
<td style="text-align: right;">0.12</td>
<td style="text-align: right;">0.38</td>
<td style="text-align: right;">0.45</td>
<td style="text-align: right;">0.54</td>
<td style="text-align: right;">0.62</td>
<td style="text-align: right;">0.87</td>
<td style="text-align: left;">▇▇▆▅▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">rm</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">6.28</td>
<td style="text-align: right;">0.70</td>
<td style="text-align: right;">3.56</td>
<td style="text-align: right;">5.89</td>
<td style="text-align: right;">6.21</td>
<td style="text-align: right;">6.62</td>
<td style="text-align: right;">8.78</td>
<td style="text-align: left;">▁▂▇▂▁</td>
</tr>
<tr class="odd">
<td style="text-align: left;">age</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">68.57</td>
<td style="text-align: right;">28.15</td>
<td style="text-align: right;">2.90</td>
<td style="text-align: right;">45.02</td>
<td style="text-align: right;">77.50</td>
<td style="text-align: right;">94.07</td>
<td style="text-align: right;">100.00</td>
<td style="text-align: left;">▂▂▂▃▇</td>
</tr>
<tr class="even">
<td style="text-align: left;">dis</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3.80</td>
<td style="text-align: right;">2.11</td>
<td style="text-align: right;">1.13</td>
<td style="text-align: right;">2.10</td>
<td style="text-align: right;">3.21</td>
<td style="text-align: right;">5.19</td>
<td style="text-align: right;">12.13</td>
<td style="text-align: left;">▇▅▂▁▁</td>
</tr>
<tr class="odd">
<td style="text-align: left;">rad</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">9.55</td>
<td style="text-align: right;">8.71</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">4.00</td>
<td style="text-align: right;">5.00</td>
<td style="text-align: right;">24.00</td>
<td style="text-align: right;">24.00</td>
<td style="text-align: left;">▇▂▁▁▃</td>
</tr>
<tr class="even">
<td style="text-align: left;">tax</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">408.24</td>
<td style="text-align: right;">168.54</td>
<td style="text-align: right;">187.00</td>
<td style="text-align: right;">279.00</td>
<td style="text-align: right;">330.00</td>
<td style="text-align: right;">666.00</td>
<td style="text-align: right;">711.00</td>
<td style="text-align: left;">▇▇▃▁▇</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ptratio</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">18.46</td>
<td style="text-align: right;">2.16</td>
<td style="text-align: right;">12.60</td>
<td style="text-align: right;">17.40</td>
<td style="text-align: right;">19.05</td>
<td style="text-align: right;">20.20</td>
<td style="text-align: right;">22.00</td>
<td style="text-align: left;">▁▃▅▅▇</td>
</tr>
<tr class="even">
<td style="text-align: left;">black</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">356.67</td>
<td style="text-align: right;">91.29</td>
<td style="text-align: right;">0.32</td>
<td style="text-align: right;">375.38</td>
<td style="text-align: right;">391.44</td>
<td style="text-align: right;">396.22</td>
<td style="text-align: right;">396.90</td>
<td style="text-align: left;">▁▁▁▁▇</td>
</tr>
<tr class="odd">
<td style="text-align: left;">lstat</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">12.65</td>
<td style="text-align: right;">7.14</td>
<td style="text-align: right;">1.73</td>
<td style="text-align: right;">6.95</td>
<td style="text-align: right;">11.36</td>
<td style="text-align: right;">16.96</td>
<td style="text-align: right;">37.97</td>
<td style="text-align: left;">▇▇▅▂▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">medv</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">22.53</td>
<td style="text-align: right;">9.20</td>
<td style="text-align: right;">5.00</td>
<td style="text-align: right;">17.02</td>
<td style="text-align: right;">21.20</td>
<td style="text-align: right;">25.00</td>
<td style="text-align: right;">50.00</td>
<td style="text-align: left;">▂▇▅▁▁</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="dicionário-de-dados" class="level3">
<h3 class="anchored" data-anchor-id="dicionário-de-dados">Dicionário de dados</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Descrição das variáveis</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>utils<span class="sc">::</span><span class="fu">help</span>(Boston)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<table class="table">
<colgroup>
<col style="width: 15%">
<col style="width: 84%">
</colgroup>
<thead>
<tr class="header">
<th><strong>Variável</strong></th>
<th><strong>Descrição</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>crim</td>
<td>Per capita crime rate by town</td>
</tr>
<tr class="even">
<td>zn</td>
<td>Proportion of residential land zoned for lots over 25000.00 sq.ft</td>
</tr>
<tr class="odd">
<td>indus</td>
<td>Proportion of non-retail business acres per town</td>
</tr>
<tr class="even">
<td>chas</td>
<td>Charles River dummy variable (= 1.00 if tract bounds river; 0.00 otherwise)</td>
</tr>
<tr class="odd">
<td>nox</td>
<td>Nitrogen oxides concentration (parts per 10.00 million)</td>
</tr>
<tr class="even">
<td>rm</td>
<td>Average number of rooms per dwelling</td>
</tr>
<tr class="odd">
<td>age</td>
<td>Proportion of owner-occupied units built prior to 1940.00</td>
</tr>
<tr class="even">
<td>dis</td>
<td>Weighted mean of distances to five Boston employment centres</td>
</tr>
<tr class="odd">
<td>rad</td>
<td>Index of accessibility to radial highwayI</td>
</tr>
<tr class="even">
<td>tax</td>
<td>Full-value property-tax rate per $10,000</td>
</tr>
<tr class="odd">
<td>ptratio</td>
<td>Pupil-teacher ratio by town</td>
</tr>
<tr class="even">
<td>black</td>
<td>1000.00 (Bk - 0.63)^2 Where Bk is the proportion of blacks by town</td>
</tr>
<tr class="odd">
<td>lstat</td>
<td>Lower status of the population (percent)</td>
</tr>
<tr class="even">
<td>medv</td>
<td>Median value of owner-occupied homes in $1000s.</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="exercício-1" class="level2">
<h2 class="anchored" data-anchor-id="exercício-1">Exercício 1</h2>
<p class="question">
Faça um gráfico de dispersão entre <code>medv</code> e <code>rm</code>.
</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>grafico_exercicio_01 <span class="ot">&lt;-</span> MASS<span class="sc">::</span>Boston <span class="sc">|&gt;</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(medv, rm) <span class="sc">|&gt;</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  ggplot2<span class="sc">::</span><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>  ggplot2<span class="sc">::</span><span class="fu">aes</span>(<span class="at">x =</span> rm, <span class="at">y =</span> medv) <span class="sc">+</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>  ggplot2<span class="sc">::</span><span class="fu">geom_point</span>(<span class="at">shape =</span> <span class="dv">1</span>, <span class="at">color =</span> <span class="st">"#EAC435"</span>) <span class="sc">+</span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>  ggplot2<span class="sc">::</span><span class="fu">labs</span>(</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Gráfico de dispersão"</span>,</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"Valor mediano(medv) x número médio de quartos (rm)"</span></span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>  ggplot2<span class="sc">::</span><span class="fu">theme_classic</span>() <span class="sc">+</span></span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>  ggplot2<span class="sc">::</span><span class="fu">theme</span>(<span class="at">panel.background =</span> ggplot2<span class="sc">::</span><span class="fu">element_rect</span>(<span class="at">fill =</span> <span class="st">"#000000"</span>))</span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a>grafico_exercicio_01</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/exercicio_01_grafico_dispersão_medv_rm-1.png" class="img-fluid figure-img" style="width:92.0%"></p>
</figure>
</div>
</div>
</div>
<figcaption>
Gráfico 01 - gráfico de dispersão dos pares valor mediano das casas e número médio de quartos.
</figcaption>
</section>
<section id="exercício-2" class="level2">
<h2 class="anchored" data-anchor-id="exercício-2">Exercício 2</h2>
<p class="question">
Ajuste um modelo de regressão linear simples utilizando <code>medv</code> como resposta e <code>rm</code> como explicativa e guarde em objeto chamado <code>mod_simples</code>. Consulte o <code>summary(mod_simples)</code> em seguida.
</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>mod_simples <span class="ot">&lt;-</span> stats<span class="sc">::</span><span class="fu">lm</span>(medv <span class="sc">~</span> rm, <span class="at">data =</span> MASS<span class="sc">::</span>Boston)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod_simples)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
stats::lm(formula = medv ~ rm, data = MASS::Boston)

Residuals:
    Min      1Q  Median      3Q     Max 
-23.346  -2.547   0.090   2.986  39.433 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  -34.671      2.650  -13.08   &lt;2e-16 ***
rm             9.102      0.419   21.72   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 6.616 on 504 degrees of freedom
Multiple R-squared:  0.4835,    Adjusted R-squared:  0.4825 
F-statistic: 471.8 on 1 and 504 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
</section>
<section id="exercício-3" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="exercício-3">Exercício 3</h2>
<div class="page-columns page-full"><p></p><div class="no-row-height column-margin column-container"><span class="aside">Para <span class="citation" data-cites="lantzbrettMachineLearning2013">Lantz (<a href="#ref-lantzbrettMachineLearning2013" role="doc-biblioref">2013</a>)</span>, A regressão linear simples define a relação entre uma variável dependente e uma única variável preditora independente usando uma linha definida por uma equação da seguinte forma: <span class="math inline">\(y = \beta_{0} + \beta_{1}x\)</span>. (..) O <em>intercept</em> descreve onde a linha cruza o eixo y, enquanto o <em>slope</em> descreve a mudança de y dado um aumento de x. (tradução nossa <a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>)</span></div></div>
<p class="question">
Sabendo que <code>medv</code> é o preço mediano das habitações do bairro e o <code>rm</code> é o número médio de quartos por habitação,
</p>
<ul>
<li>
Interprete o parâmetro <code>(Intercept)</code>.
</li>
</ul>
<p>No exercício 02, ajustamos o modelo de regressão linear considerando <code>medv</code> como variável resposta e <code>rm</code> como variável explicativa. O objetivo era encontrar as <strong>estimadores dos mínimos quadrados</strong>, ou seja, os parâmetros <span class="math inline">\(\hat{\beta }_{0}\)</span> e <span class="math inline">\(\hat{\beta }_{1}\)</span>, os quais são os estimadores de <span class="math inline">\({\beta }_{0}\)</span> e <span class="math inline">\({\beta }_{1}\)</span>, de modo que o modelo linear resultante fosse o mais próximo possível dos n pontos de dados. Foi utilizada a abordagem dos mínimos quadrados, em que um ajuste foi feito minimizando a soma dos erros ao quadrado.</p>
<p>O parâmetro <code>intercept</code> obtido pela função lm do pacote ‘stats’ corresponde ao parâmetro <span class="math inline">\(\hat{\beta }_{0}\)</span>, e pode ser obtido pela seguinte equação de estimação:</p>
<p><span class="math display">\[\hat{\beta }_{0}   = \bar{y} - \hat{\beta }_{1}\bar{x},\]</span></p>
<p><br> e pode ser interpretado como <strong>o valor provável do preço mediano das habitações para aquelas com o número médio de quartos igual a zero, <em>i.e.</em>, uma habitaçao com x = 0</strong>. <br><br><br></p>
<ul>
<li>
Interprete o parâmetro <code>rm</code>.
</li>
</ul>
<p>O parâmetro <code>rm</code>, conhecido por <code>slope</code>, representa o parâmetro <span class="math inline">\(\hat{\beta }_{1}\)</span> do modelo e pode ser obtido pela equação de estimação: <br><br></p>
<p><span class="math display">\[\hat{\beta }_{1}  = \frac{\sum_{i=1}^{n}\left ( x_{i} - \bar{x} \right )(y_{i}-\bar{y})}{\sum_{i=1}^{n }(x_{i} - \bar{x})^{2}},\]</span></p>
<p><br></p>
<p>e <strong>representa o aumento esperado do preço mediano das habitações para cada aumento na média de quartos de uma unidade no total de quartos da habitação, ou seja, a cada acréscimo de um quarto o preço mediano da casa aumenta em média US$9102.11</strong>. <br><br><br></p>
<ul>
<li>
O número de quartos está associado com o valor da habitação? Por quê?
</li>
</ul>
<p>Sim, o número de quartos está associado com o valor da habitação.</p>
<p>Vamos analisar esta questão, partindo do teste de hipótese: ‘O número médio de quartos por habitação <strong>não</strong> possui associação com o valor mediano das casas’ <br><br></p>
<p><span class="math inline">\(\left\{ \begin{array}{cl} H0 &amp; : \ \hat{\beta }_{1} = 0 \\ Ha &amp; : \ \hat{\beta }_{1} \neq 0 \end{array} \right.\)</span></p>
<p><br></p>
<p>Ao analisar os resultados obtidos no exercício 02, observa-se que que o <code>t-value</code> para o parâmetro <code>rm</code> (número médio de quartos por habitação) foi de 21,72, o que torna absurda a hipótese nula, pois este valor afasta-se significativamente da zona provável de valores para a hipótese analisada.</p>
<p>O <code>valor-p</code>, que representa a probabilidade de encontrarmos o valor de 21,72 (<em>t-value</em>) na zona provável de valores para a hipótese de que o número médio de quartos por habitação <strong>não</strong> possui associação com o valor mediano das casas é muito próximo de zero, menor que os níveis de significância mais usuais (0.01, 0.05, 0.10), portanto podemos <strong>refutar</strong> a hipótese nula.</p>
<p>Conclui-se, portanto, que <strong>o número médio de quartos está associado ao valor mediano das habitações</strong>.</p>
</section>
<section id="exercício-4" class="level2">
<h2 class="anchored" data-anchor-id="exercício-4">Exercício 4</h2>
<p class="question">
Consulte as saídas das seguintes funções do pacote stats.
</p>
<ul>
<li>
coef(mod_simples)
</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>stats<span class="sc">::</span><span class="fu">coef</span>(mod_simples)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)          rm 
 -34.670621    9.102109 </code></pre>
</div>
</div>
<p>A funçao <code>coef</code> extrai coeficientes de objetos que retornam de funções de modelagem.</p>
<ul>
<li>
confint(mod_simples)
</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(mod_simples)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                 2.5 %     97.5 %
(Intercept) -39.876641 -29.464601
rm            8.278855   9.925363</code></pre>
</div>
</div>
<p>A funçao <code>confint</code> permite construir os Intervalos de Confiança (95%) para os coeficientes da regressão por meio do comando acima.</p>
<ul>
<li>
predict(mod_simples)
</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(mod_simples) <span class="sc">|&gt;</span> </span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>(<span class="at">n =</span> <span class="dv">30</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       1        2        3        4        5        6        7        8 
25.17575 23.77402 30.72803 29.02594 30.38215 23.85594 20.05126 21.50760 
       9       10       11       12       13       14       15       16 
16.58335 19.97844 23.37353 20.02395 18.93170 19.47783 20.81584 18.43108 
      17       18       19       20       21       22       23       24 
19.35040 19.85101 14.99049 17.45716 16.02813 19.62346 21.23453 18.23994 
      25       26       27       28       29       30 
19.25027 16.29209 18.23994 20.36983 24.44758 26.07685 </code></pre>
</div>
</div>
<p>A função <code>predict</code> possibilita fazer inferência sobre os valores preditos das respostas média e individual de Y. Acima tem-se os 30 primeiros valores.</p>
<ul>
<li>
predict(mod_simples, interval = “confidence”)
</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(mod_simples, <span class="at">interval =</span> <span class="st">"confidence"</span>) <span class="sc">|&gt;</span> </span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>(<span class="at">n =</span> <span class="dv">30</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        fit      lwr      upr
1  25.17575 24.55039 25.80110
2  23.77402 23.18536 24.36269
3  30.72803 29.78817 31.66790
4  29.02594 28.20203 29.84984
5  30.38215 29.46676 31.29755
6  23.85594 23.26582 24.44606
7  20.05126 19.43134 20.67118
8  21.50760 20.92234 22.09285
9  16.58335 15.79375 17.37296
10 19.97844 19.35611 20.60078
11 23.37353 22.79069 23.95637
12 20.02395 19.40313 20.64477
13 18.93170 18.26837 19.59503
14 19.47783 18.83730 20.11835
15 20.81584 20.21747 21.41420
16 18.43108 17.74439 19.11778
17 19.35040 18.70482 19.99598
18 19.85101 19.22431 20.47772
19 14.99049 14.09646 15.88451
20 17.45716 16.71914 18.19518
21 16.02813 15.20347 16.85278
22 19.62346 18.98851 20.25841
23 21.23453 20.64486 21.82420
24 18.23994 17.54375 18.93613
25 19.25027 18.60060 19.89994
26 16.29209 15.48430 17.09988
27 18.23994 17.54375 18.93613
28 20.36983 19.75975 20.97991
29 24.44758 23.84432 25.05083
30 26.07685 25.41604 26.73767</code></pre>
</div>
</div>
<p>A função <code>predict</code> também permite a obtenção das correspondentes estimativas pontuais e intervalar (95% de confiança). Acima tem-se os 30 primeiros valores.</p>
</section>
<section id="exercício-5" class="level2">
<h2 class="anchored" data-anchor-id="exercício-5">Exercício 5</h2>
<p class="question">
Usando o data.frame gerado por <code>augment(mod_simples)</code> faça um gráfico de <code>medv</code> versus <code>rm</code> e em seguida desenhe a reta ajustada do <code>mod_simples</code>.
</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>broom<span class="sc">::</span><span class="fu">augment</span>(mod_simples)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 506 × 8
    medv    rm .fitted  .resid    .hat .sigma     .cooksd .std.resid
   &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt;       &lt;dbl&gt;      &lt;dbl&gt;
 1  24    6.58    25.2 -1.18   0.00231   6.62 0.0000367      -0.178 
 2  21.6  6.42    23.8 -2.17   0.00205   6.62 0.000111       -0.329 
 3  34.7  7.18    30.7  3.97   0.00523   6.62 0.000952        0.602 
 4  33.4  7.00    29.0  4.37   0.00402   6.62 0.000885        0.662 
 5  36.2  7.15    30.4  5.82   0.00496   6.62 0.00194         0.882 
 6  28.7  6.43    23.9  4.84   0.00206   6.62 0.000555        0.733 
 7  22.9  6.01    20.1  2.85   0.00227   6.62 0.000212        0.431 
 8  27.1  6.17    21.5  5.59   0.00203   6.62 0.000727        0.846 
 9  16.5  5.63    16.6 -0.0834 0.00369   6.62 0.000000295    -0.0126
10  18.9  6.00    20.0 -1.08   0.00229   6.62 0.0000306      -0.163 
# … with 496 more rows
# ℹ Use `print(n = ...)` to see more rows</code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>graf_ex05 <span class="ot">&lt;-</span> broom<span class="sc">::</span><span class="fu">augment</span>(mod_simples) <span class="sc">|&gt;</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(medv, rm) <span class="sc">|&gt;</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>  ggplot2<span class="sc">::</span><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>  ggplot2<span class="sc">::</span><span class="fu">aes</span>(</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> medv,</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> rm</span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>  ggplot2<span class="sc">::</span><span class="fu">geom_point</span>(<span class="at">shape =</span> <span class="dv">1</span>, <span class="at">color =</span> <span class="st">"#EAC435"</span>) <span class="sc">+</span></span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>  ggplot2<span class="sc">::</span><span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">color =</span> <span class="st">"#F3752B"</span>) <span class="sc">+</span></span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>  ggplot2<span class="sc">::</span><span class="fu">labs</span>(</span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Gráfico de dispersão e modelo de regressão linear ajustado"</span>,</span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"Valor mediano das casas (medv) x número médio de quartos (rm)"</span></span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a>  ggpubr<span class="sc">::</span><span class="fu">stat_regline_equation</span>(ggplot2<span class="sc">::</span><span class="fu">aes</span>(<span class="at">label =</span> <span class="fu">paste</span>(..eq.label..,</span>
<span id="cb20-15"><a href="#cb20-15" aria-hidden="true" tabindex="-1"></a>    ..rr.label..,</span>
<span id="cb20-16"><a href="#cb20-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">sep =</span> <span class="st">"*plain(</span><span class="sc">\"</span><span class="st">,</span><span class="sc">\"</span><span class="st">)~~"</span></span>
<span id="cb20-17"><a href="#cb20-17" aria-hidden="true" tabindex="-1"></a>  )),</span>
<span id="cb20-18"><a href="#cb20-18" aria-hidden="true" tabindex="-1"></a>  <span class="at">color =</span> <span class="st">"#F3752B"</span></span>
<span id="cb20-19"><a href="#cb20-19" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb20-20"><a href="#cb20-20" aria-hidden="true" tabindex="-1"></a>  ggplot2<span class="sc">::</span><span class="fu">theme_classic</span>() <span class="sc">+</span></span>
<span id="cb20-21"><a href="#cb20-21" aria-hidden="true" tabindex="-1"></a>  ggplot2<span class="sc">::</span><span class="fu">theme</span>(<span class="at">panel.background =</span> ggplot2<span class="sc">::</span><span class="fu">element_rect</span>(<span class="at">fill =</span> <span class="st">"#000000"</span>))</span>
<span id="cb20-22"><a href="#cb20-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-23"><a href="#cb20-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-24"><a href="#cb20-24" aria-hidden="true" tabindex="-1"></a>graf_ex05</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/exercicio5_grafico_dispersao-1.png" class="img-fluid figure-img" style="width:90.0%"></p>
</figure>
</div>
</div>
</div>
<figcaption>
Gráfico 02 - Modelo linear ajustado e seu coeficiente de determinação R<sup>2</sup>.
</figcaption>
</section>
<section id="exercício-6" class="level2">
<h2 class="anchored" data-anchor-id="exercício-6">Exercício 6</h2>
<p class="question">
Faça um gráfico de resíduos. Coloque os <strong>resíduos</strong> no eixo Y e os <strong>valores ajustados</strong> no eixo X.
</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>residuos <span class="ot">&lt;-</span> broom<span class="sc">::</span><span class="fu">augment</span>(mod_simples) <span class="sc">|&gt;</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(.resid, .fitted) <span class="sc">|&gt;</span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>  ggplot2<span class="sc">::</span><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>  ggplot2<span class="sc">::</span><span class="fu">aes</span>(<span class="at">x =</span> .fitted, <span class="at">y =</span> .resid) <span class="sc">+</span></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>  ggplot2<span class="sc">::</span><span class="fu">geom_point</span>(<span class="at">shape =</span> <span class="dv">1</span>, <span class="at">size =</span> <span class="dv">2</span>, <span class="at">color =</span> <span class="st">"#EAC435"</span>) <span class="sc">+</span></span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>  ggplot2<span class="sc">::</span><span class="fu">geom_line</span>(ggplot2<span class="sc">::</span><span class="fu">aes</span>(<span class="at">x =</span> .fitted, <span class="at">y =</span> <span class="dv">0</span>, <span class="at">color =</span> <span class="st">"red"</span>),</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">linetype =</span> <span class="dv">2</span></span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>  ggplot2<span class="sc">::</span><span class="fu">labs</span>(</span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Residuals x Fitted"</span>,</span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Residuals"</span>,</span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Fitted Values"</span></span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb22-14"><a href="#cb22-14" aria-hidden="true" tabindex="-1"></a>  ggplot2<span class="sc">::</span><span class="fu">theme_classic</span>() <span class="sc">+</span></span>
<span id="cb22-15"><a href="#cb22-15" aria-hidden="true" tabindex="-1"></a>  ggplot2<span class="sc">::</span><span class="fu">theme</span>(</span>
<span id="cb22-16"><a href="#cb22-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">panel.background =</span> ggplot2<span class="sc">::</span><span class="fu">element_rect</span>(<span class="at">fill =</span> <span class="st">"#000000"</span>),</span>
<span id="cb22-17"><a href="#cb22-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">legend.position =</span> <span class="st">"none"</span></span>
<span id="cb22-18"><a href="#cb22-18" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb22-19"><a href="#cb22-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-20"><a href="#cb22-20" aria-hidden="true" tabindex="-1"></a>residuos</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/grafico_exercicio_06_residuos-1.png" class="img-fluid figure-img" style="width:90.0%"></p>
</figure>
</div>
</div>
</div>
<figcaption>
Gráfico 03 - gráfico dos resíduos e valores ajustados.
</figcaption>
</section>
<section id="exercício-7" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="exercício-7">Exercício 7</h2>
<p class="question">
Observe os gráficos de <code>plot(mod_simples)</code>.
</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>op <span class="ot">&lt;-</span> <span class="fu">par</span>(<span class="at">bg =</span> <span class="st">"#000000"</span>)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>graphics<span class="sc">::</span><span class="fu">par</span>(</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>),</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">bty =</span> <span class="st">"l"</span>,</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">col =</span> <span class="st">"#FFFFFF"</span></span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(mod_simples,</span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">bg =</span> <span class="fu">par</span>(<span class="st">"bg"</span>),</span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">col =</span> <span class="st">"#EAC435"</span>,</span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">col.axis =</span> <span class="st">"#FFFFFF"</span>,</span>
<span id="cb23-12"><a href="#cb23-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">col.lab =</span> <span class="st">"thistle"</span>, </span>
<span id="cb23-13"><a href="#cb23-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">which =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>)</span>
<span id="cb23-14"><a href="#cb23-14" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/funçoes_built_in_modelo_simples-1.png" class="img-fluid figure-img" width="662"></p>
</figure>
</div>
</div>
</div>
<figcaption>
Gráfico 04 - Resíduos x Valores padronizados e QQ-Plot .
</figcaption>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>op <span class="ot">&lt;-</span> <span class="fu">par</span>(<span class="at">bg =</span> <span class="st">"#000000"</span>)</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>graphics<span class="sc">::</span><span class="fu">par</span>(</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>),</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">bty =</span> <span class="st">"l"</span>,</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">col =</span> <span class="st">"#FFFFFF"</span></span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(mod_simples,</span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">bg =</span> <span class="fu">par</span>(<span class="st">"bg"</span>),</span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">col =</span> <span class="st">"#EAC435"</span>,</span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">col.axis =</span> <span class="st">"#FFFFFF"</span>,</span>
<span id="cb24-12"><a href="#cb24-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">col.lab =</span> <span class="st">"thistle"</span>, </span>
<span id="cb24-13"><a href="#cb24-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">which =</span> <span class="fu">c</span>(<span class="dv">3</span>,<span class="dv">5</span>)</span>
<span id="cb24-14"><a href="#cb24-14" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/grafico_exercicio07-1.png" class="img-fluid figure-img" width="662"></p>
</figure>
</div>
</div>
</div>
<figcaption>
Gráfico 05 - Resíduos padronizados x Valores padronizados e Resíduos x alavancagem .
</figcaption>
<br><br> 
<div class="no-row-height column-margin column-container"><span class="aside">De acordo com <span class="citation" data-cites="morettinpedroalbertoEstatisticaCienciaDados2022">Morettin e Singer, Julio da Motta (<a href="#ref-morettinpedroalbertoEstatisticaCienciaDados2022" role="doc-biblioref">2022</a>)</span>, ‘Uma das ferramentas mais úteis para a avaliação da qualidade do ajuste de modelos de regressão é o <strong>gráfico de resíduos</strong> em que os resíduos são dispostos no eixo das ordenadas e os correspondentes valores da variável explicativa no eixo das abscissas (..) Os resíduos padronizados são adimensionais e têm variância igual a 1, independentemente da variância dos erros. Além disso, para erros com distribuição normal, cerca de 99% dos resíduos padronizados tem valor entre -3 e +3’.</span></div><p class="question">
Apenas pela inspeção visual, responda: existem outliers? Eles são pontos de alavanca?
</p>
<p><strong>Sim. Existem outliers.</strong></p>
<p>A existência de <em>outliers</em> e de pontos de alavancagem pode ser analisada por meio do gráfico ‘Residuals vs Leverage’. A partir dele, os dados que extrapolam os valores de -3 e +3 são identificados como <em>outliers</em> como nos casos #369, #366 e #365. Estes números correspondem ao número da linha do dado no <em>dataset</em>.</p>
<p><strong>Pelo gráfico, não existem pontos influentes ou pontos alavanca</strong> (<em>high leverage points</em>). Note que pouco vemos as linhas de distância de Cook (linhas tracejadas nos cantos superior direito e inferior esquerdo) e que todos os casos estão dentro das linhas de distância de Cook</p>
</section>
<section id="exercício-8" class="level2">
<h2 class="anchored" data-anchor-id="exercício-8">Exercício 8</h2>
<p class="question">
Ajuste um modelo <code>mod_multiplo</code> para <code>medv</code> explicado por <code>rm</code> e <code>crim</code>. Consulte o <code>summary(mod_multiplo)</code> em seguida.
</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>mod_multiplo <span class="ot">&lt;-</span> stats<span class="sc">::</span><span class="fu">lm</span>(medv <span class="sc">~</span> rm <span class="sc">+</span> crim, <span class="at">data =</span> MASS<span class="sc">::</span>Boston)</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod_multiplo, <span class="at">scientific =</span> <span class="cn">FALSE</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
stats::lm(formula = medv ~ rm + crim, data = MASS::Boston)

Residuals:
    Min      1Q  Median      3Q     Max 
-21.608  -2.835  -0.380   2.592  38.839 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -29.24472    2.58809 -11.300   &lt;2e-16 ***
rm            8.39107    0.40485  20.726   &lt;2e-16 ***
crim         -0.26491    0.03307  -8.011    8e-15 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 6.237 on 503 degrees of freedom
Multiple R-squared:  0.542, Adjusted R-squared:  0.5401 
F-statistic: 297.6 on 2 and 503 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p><br></p>
</section>
<section id="exercício-9" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="exercício-9">Exercício 9</h2>
<div class="page-columns page-full"><p></p><div class="no-row-height column-margin column-container"><span class="aside">Conforme o <em>post</em> <span class="citation" data-cites="bommaeUnderstandingDiagnosticPlots2015">Bommae (<a href="#ref-bommaeUnderstandingDiagnosticPlots2015" role="doc-biblioref">2015</a>)</span>, de Bommae King, da Biblioteca da Universidade da Virginia, o gráfico ‘Residuals x Fitted’ nos mostra que a existência de uma relação linear entre a variável resposta e a variável explicativa ocorre quando encontramos resíduos igualmente espalhados em torno de uma linha horizontal sem padrões distintos, sendo isto é uma boa indicação de que as variáveis possuem relação linear. (texto original <a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a>)</span></div></div>
<p class="question">
Qual modelo ficou melhor: <code>mod_simples</code> ou <code>mod_multiplo</code>? Qual critério você utilizou para decidir o melhor?
</p>
<p>O critério utilizado na comparação dos modelos será o coeficiente de determinação ajustado. Abaixo, segue a explicação.</p>
<p>Conforme <span class="citation" data-cites="morettinpedroalbertoEstatisticaCienciaDados2022">Morettin e Singer, Julio da Motta (<a href="#ref-morettinpedroalbertoEstatisticaCienciaDados2022" role="doc-biblioref">2022</a>)</span>, ’Uma vez ajustado o modelo, convém avaliar a qualidade do ajuste e um dos indicadores mais utilizados para essa finalidade é o <strong>coeficiente de determinação</strong> definido como:</p>
<p><span class="math display">\[R^{2} = \frac{SQTot - SQRes}{SQTot} = \frac{SQReg}{SQTot} = 1 - \frac{SQRes}{SQTot},\]</span></p>
<p>(..) Em essência, esse coeficiente mede a porcentagem da variação total dos valores da variável resposta (yi) em relação à sua média (<span class="math inline">\(\bar{y}\)</span>) explicada pelo modelo de regressão’.</p>
<div class="page-columns page-full"><p></p><div class="no-row-height column-margin column-container"><span class="aside">Segundo <span class="citation" data-cites="pianezzerguilhermeaugustoModelagemEstatistica2020">Pianezzer (<a href="#ref-pianezzerguilhermeaugustoModelagemEstatistica2020" role="doc-biblioref">2020</a>)</span>, ‘pode-se provar que R<sup>2</sup> está contido entre 0 e 1. Alguns livros chamam de <em>coeficiente de determinação</em> o termo’ R, tal que <span class="math inline">\(-1 \le R \le 1\)</span>; entretanto, utilizar R<sup>2</sup>, tal que <span class="math inline">\(0 \le R^{2} \le 1\)</span> facilita a análise ao evitar operar com números negativos. Dessa forma, podemos afirmar que quanto mais <span class="math inline">\(R^{2} \to 1\)</span>, mais forte é o poder explicativo do modelo linear. Quanto mais <span class="math inline">\(R^{2} \to 0\)</span>, menos podemos confiar no modelo, visto que os dados não se aproximam da reta.’</span></div></div>
<p>Como a comparação ocorre entre o modelo linear simples e o modelo linear múltiplo, vamos utilizar o <strong>coeficiente de determinação ajustado</strong>.</p>
<p><span class="math display">\[R^{2}_{ajustado} = 1 - \frac{SQRes}{SQTot} . \frac{N-1}{N - p}, \]</span></p>
<p>em que p é o número de parâmetros do modelo.</p>
<p>Na tabela abaixo, temos os resultados dos modelos de regressão linear simples e múltiplo.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>sjPlot<span class="sc">::</span><span class="fu">tab_model</span>(mod_simples, mod_multiplo)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<table style="border-collapse:collapse; border:none;">
<tbody><tr>
<th style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm;  text-align:left; ">&nbsp;</th>
<th colspan="3" style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm; ">medv</th>
<th colspan="3" style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm; ">medv</th>
</tr>
<tr>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  text-align:left; ">Predictors</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">Estimates</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">CI</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">p</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">Estimates</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">CI</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  col7">p</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">(Intercept)</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">-34.67</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">-39.88&nbsp;–&nbsp;-29.46</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "><strong>&lt;0.001</strong></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">-29.24</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">-34.33&nbsp;–&nbsp;-24.16</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col7"><strong>&lt;0.001</strong></td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">rm</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">9.10</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">8.28&nbsp;–&nbsp;9.93</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "><strong>&lt;0.001</strong></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">8.39</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">7.60&nbsp;–&nbsp;9.19</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col7"><strong>&lt;0.001</strong></td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">crim</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">-0.26</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">-0.33&nbsp;–&nbsp;-0.20</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col7"><strong>&lt;0.001</strong></td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm; border-top:1px solid;">Observations</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left; border-top:1px solid;" colspan="3">506</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left; border-top:1px solid;" colspan="3">506</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;">R<sup>2</sup> / R<sup>2</sup> adjusted</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="3">0.484 / 0.483</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="3">0.542 / 0.540</td>
</tr>

</tbody></table>

</div>
</div>
<div class="page-columns page-full"><p><br> </p><div class="no-row-height column-margin column-container"><span class="aside">De acordo com <span class="citation" data-cites="larsonronEstatisticaAplicada1941">Larson e Farber (<a href="#ref-larsonronEstatisticaAplicada1941" role="doc-biblioref">1941</a>)</span>, o quadrado do coeficiente de correlação é chamado de coeficiente de determinação. Pode-se mostrar que o coeficiente de determinação é igual a razão entre a variação explicada e a variação total</span></div></div>
<p><strong>O modelo <code>mod_multiplo</code> ficou melhor</strong>, pois possui maior coeficiente de determinação ajustado <span class="math inline">\(R^{2}_{ajustado}\)</span> = 0.540, melhor que o obtido pelo modelo simples, cujo coeficiente de determinação foi de 0.483.</p>
<p>Isto significa que no modelo múltiplo 54% da variação de y (valor mediano da casa) pode ser explicado pela relação entre x (número médio de quartos) e y. Os demais 46% da variação não são explicados pelo modelo devido a outros fatores ou erros amostrais.</p>
</section>
<section id="exercício-10" class="level2">
<h2 class="anchored" data-anchor-id="exercício-10">Exercício 10</h2>
<p class="question">
Ajuste um modelo <code>mod_completo</code> para <code>medv</code> explicado por todas as demais colunas. DICA: na fórmula <code>medv ~ .</code>, o ponto significa “todas as variáveis, tirando medv”.
</p>
<ul>
<li>
Consulte o <code>summary(mod_completo)</code> em seguida.
</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>mod_completo <span class="ot">&lt;-</span> stats<span class="sc">::</span><span class="fu">lm</span>(medv <span class="sc">~</span> ., <span class="at">data =</span> MASS<span class="sc">::</span>Boston)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod_completo)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
stats::lm(formula = medv ~ ., data = MASS::Boston)

Residuals:
    Min      1Q  Median      3Q     Max 
-15.595  -2.730  -0.518   1.777  26.199 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  3.646e+01  5.103e+00   7.144 3.28e-12 ***
crim        -1.080e-01  3.286e-02  -3.287 0.001087 ** 
zn           4.642e-02  1.373e-02   3.382 0.000778 ***
indus        2.056e-02  6.150e-02   0.334 0.738288    
chas         2.687e+00  8.616e-01   3.118 0.001925 ** 
nox         -1.777e+01  3.820e+00  -4.651 4.25e-06 ***
rm           3.810e+00  4.179e-01   9.116  &lt; 2e-16 ***
age          6.922e-04  1.321e-02   0.052 0.958229    
dis         -1.476e+00  1.995e-01  -7.398 6.01e-13 ***
rad          3.060e-01  6.635e-02   4.613 5.07e-06 ***
tax         -1.233e-02  3.760e-03  -3.280 0.001112 ** 
ptratio     -9.527e-01  1.308e-01  -7.283 1.31e-12 ***
black        9.312e-03  2.686e-03   3.467 0.000573 ***
lstat       -5.248e-01  5.072e-02 -10.347  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 4.745 on 492 degrees of freedom
Multiple R-squared:  0.7406,    Adjusted R-squared:  0.7338 
F-statistic: 108.1 on 13 and 492 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<ul>
<li>
Qual modelo ficou melhor: <code>mod_simples</code>, <code>mod_multiplo</code> ou <code>mod_completo</code>?
</li>
</ul>
<p>Pode-se visualizar os dados dos três modelos abaixo:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>sjPlot<span class="sc">::</span><span class="fu">tab_model</span>(mod_simples, mod_multiplo, mod_completo)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<table style="border-collapse:collapse; border:none;">
<tbody><tr>
<th style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm;  text-align:left; ">&nbsp;</th>
<th colspan="3" style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm; ">medv</th>
<th colspan="3" style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm; ">medv</th>
<th colspan="3" style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm; ">medv</th>
</tr>
<tr>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  text-align:left; ">Predictors</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">Estimates</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">CI</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">p</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">Estimates</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">CI</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  col7">p</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  col8">Estimates</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  col9">CI</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  0">p</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">(Intercept)</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">-34.67</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">-39.88&nbsp;–&nbsp;-29.46</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "><strong>&lt;0.001</strong></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">-29.24</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">-34.33&nbsp;–&nbsp;-24.16</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col7"><strong>&lt;0.001</strong></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col8">36.46</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col9">26.43&nbsp;–&nbsp;46.49</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  0"><strong>&lt;0.001</strong></td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">rm</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">9.10</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">8.28&nbsp;–&nbsp;9.93</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "><strong>&lt;0.001</strong></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">8.39</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">7.60&nbsp;–&nbsp;9.19</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col7"><strong>&lt;0.001</strong></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col8">3.81</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col9">2.99&nbsp;–&nbsp;4.63</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  0"><strong>&lt;0.001</strong></td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">crim</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">-0.26</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">-0.33&nbsp;–&nbsp;-0.20</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col7"><strong>&lt;0.001</strong></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col8">-0.11</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col9">-0.17&nbsp;–&nbsp;-0.04</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  0"><strong>0.001</strong></td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">zn</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col7"></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col8">0.05</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col9">0.02&nbsp;–&nbsp;0.07</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  0"><strong>0.001</strong></td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">indus</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col7"></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col8">0.02</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col9">-0.10&nbsp;–&nbsp;0.14</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  0">0.738</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">chas</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col7"></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col8">2.69</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col9">0.99&nbsp;–&nbsp;4.38</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  0"><strong>0.002</strong></td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">nox</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col7"></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col8">-17.77</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col9">-25.27&nbsp;–&nbsp;-10.26</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  0"><strong>&lt;0.001</strong></td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">age</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col7"></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col8">0.00</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col9">-0.03&nbsp;–&nbsp;0.03</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  0">0.958</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">dis</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col7"></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col8">-1.48</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col9">-1.87&nbsp;–&nbsp;-1.08</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  0"><strong>&lt;0.001</strong></td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">rad</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col7"></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col8">0.31</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col9">0.18&nbsp;–&nbsp;0.44</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  0"><strong>&lt;0.001</strong></td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">tax</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col7"></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col8">-0.01</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col9">-0.02&nbsp;–&nbsp;-0.00</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  0"><strong>0.001</strong></td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">ptratio</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col7"></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col8">-0.95</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col9">-1.21&nbsp;–&nbsp;-0.70</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  0"><strong>&lt;0.001</strong></td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">black</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col7"></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col8">0.01</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col9">0.00&nbsp;–&nbsp;0.01</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  0"><strong>0.001</strong></td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">lstat</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col7"></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col8">-0.52</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col9">-0.62&nbsp;–&nbsp;-0.43</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  0"><strong>&lt;0.001</strong></td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm; border-top:1px solid;">Observations</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left; border-top:1px solid;" colspan="3">506</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left; border-top:1px solid;" colspan="3">506</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left; border-top:1px solid;" colspan="3">506</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;">R<sup>2</sup> / R<sup>2</sup> adjusted</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="3">0.484 / 0.483</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="3">0.542 / 0.540</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="3">0.741 / 0.734</td>
</tr>

</tbody></table>

</div>
</div>
<p>Com base no coeficiente de determinação ajustado, pode-se concluir que <strong>o modelo de regressão linear completo é o melhor modelo, pois possui o melhor <span class="math inline">\(R^{2}\)</span> = 0.734.</strong></p>
<p>Alternativamente, podemos avaliar os modelos segundo as métricas AIC (Akaike Information Criterion), cuja ideia básica é penalizar a inclusão de variáveis adicionais a um modelo e BIC (Bayesian Information Criterion), que é uma variante de AIC com penalidades mais fortes por incluir variáveis adicionais. Quanto menor estas métricas, melhor é o modelo.</p>
<p>A função glance do pacote broom nos fornece de forma consolidada os critérios.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>broom<span class="sc">::</span><span class="fu">glance</span>(mod_simples)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 12
  r.squared adj.r.squa…¹ sigma stati…²  p.value    df logLik   AIC   BIC devia…³
      &lt;dbl&gt;        &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;
1     0.484        0.483  6.62    472. 2.49e-74     1 -1673. 3352. 3365.  22062.
# … with 2 more variables: df.residual &lt;int&gt;, nobs &lt;int&gt;, and abbreviated
#   variable names ¹​adj.r.squared, ²​statistic, ³​deviance
# ℹ Use `colnames()` to see all variable names</code></pre>
</div>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>broom<span class="sc">::</span><span class="fu">glance</span>(mod_multiplo)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 12
  r.squared adj.r.squa…¹ sigma stati…²  p.value    df logLik   AIC   BIC devia…³
      &lt;dbl&gt;        &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;
1     0.542        0.540  6.24    298. 5.22e-86     2 -1643. 3293. 3310.  19566.
# … with 2 more variables: df.residual &lt;int&gt;, nobs &lt;int&gt;, and abbreviated
#   variable names ¹​adj.r.squared, ²​statistic, ³​deviance
# ℹ Use `colnames()` to see all variable names</code></pre>
</div>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>broom<span class="sc">::</span><span class="fu">glance</span>(mod_completo)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 12
  r.squared adj.r.squ…¹ sigma stati…²   p.value    df logLik   AIC   BIC devia…³
      &lt;dbl&gt;       &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;     &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;
1     0.741       0.734  4.75    108. 6.72e-135    13 -1499. 3028. 3091.  11079.
# … with 2 more variables: df.residual &lt;int&gt;, nobs &lt;int&gt;, and abbreviated
#   variable names ¹​adj.r.squared, ²​statistic, ³​deviance
# ℹ Use `colnames()` to see all variable names</code></pre>
</div>
</div>
<p><br></p>
<p>Segundo as métricas AIC = 3028 e BIC = 3091, <strong>também</strong> se pode concluir que <strong>o modelo de regressão completo possui o melhor resultado</strong>.</p>
<p><br></p>
<ul>
<li>
O valor estimado para o termo <code>rm</code> variou entre os três modelos? Por qual razão você acha que isso aconteceu?
</li>
</ul>
<p>À medida que adicionamos ao modelo outras váriáveis explicativas que possuem significância, acrescentamos mais informação ao modelo. <strong>A existência de outros parâmetros estimadores faz com que o valor estimado para o termo <code>rm</code> sofra a variação observada, pois outros parâmetros passaram a exercer influência sobre a variável resposta. A redução do valor de <code>rm</code> de 9.10 (modelos simples), 8.39 (modelo múltiplo) e 3.81 (modelo completo) demonstra a redução na influência desta variável sobre a variável <code>medv</code></strong> em função das demais variáveis.</p>
<p>Entretanto, deve-se evitar o fenômeno de <em>overfitting</em>, que pode ocorrer quando aumenta-se muito o número de variáveis explicativas no modelo e este perde sua capacidade de generalização.</p>
</section>
<section id="análises-complementares" class="level2">
<h2 class="anchored" data-anchor-id="análises-complementares">Análises Complementares</h2>
<p>Podemos eliminar as variáveis explicativas não influentes e então obtermos o modelo mais simples e ajustado.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>dados <span class="ot">&lt;-</span> dados <span class="ot">&lt;-</span> MASS<span class="sc">::</span>Boston</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>dados<span class="sc">$</span>indus <span class="ot">&lt;-</span> <span class="cn">NULL</span></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>dados<span class="sc">$</span>age <span class="ot">&lt;-</span> <span class="cn">NULL</span></span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>mod_final <span class="ot">&lt;-</span> <span class="fu">lm</span>(dados<span class="sc">$</span>medv <span class="sc">~</span> ., <span class="at">data =</span> dados)</span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod_final)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = dados$medv ~ ., data = dados)

Residuals:
     Min       1Q   Median       3Q      Max 
-15.5984  -2.7386  -0.5046   1.7273  26.2373 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  36.341145   5.067492   7.171 2.73e-12 ***
crim         -0.108413   0.032779  -3.307 0.001010 ** 
zn            0.045845   0.013523   3.390 0.000754 ***
chas          2.718716   0.854240   3.183 0.001551 ** 
nox         -17.376023   3.535243  -4.915 1.21e-06 ***
rm            3.801579   0.406316   9.356  &lt; 2e-16 ***
dis          -1.492711   0.185731  -8.037 6.84e-15 ***
rad           0.299608   0.063402   4.726 3.00e-06 ***
tax          -0.011778   0.003372  -3.493 0.000521 ***
ptratio      -0.946525   0.129066  -7.334 9.24e-13 ***
black         0.009291   0.002674   3.475 0.000557 ***
lstat        -0.522553   0.047424 -11.019  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 4.736 on 494 degrees of freedom
Multiple R-squared:  0.7406,    Adjusted R-squared:  0.7348 
F-statistic: 128.2 on 11 and 494 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p><br></p>
<p>Obtem-se o seguinte modelo de regressão linear múltipla: <br></p>
<div class="cell">

</div>
<p class="p1">
y=36.3411-0.1084.crim+0.0458.zn+2.7187.chas-17.376.nox+3.8016.rm-1.4927.dis+0.2996.rad-0.0118.tax-0.9465.ptradio+0.0093.black-0.5226.lstat
</p>
<p>Para compararmos os parâmetros e identificarmos aqueles mais influentes sobre a variável resposta, encontra-se seus valores dos padronizados.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>cfp <span class="ot">&lt;-</span> QuantPsyc<span class="sc">::</span><span class="fu">lm.beta</span>(mod_final)</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>cfp</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       crim          zn        chas         nox          rm         dis 
-0.10139303  0.11625575  0.07508208 -0.21892687  0.29042342 -0.34176167 
        rad         tax     ptratio       black       lstat 
 0.28365108 -0.21583160 -0.22280645  0.09222538 -0.40573493 </code></pre>
</div>
</div>
</section>
<section id="conclusão" class="level2">
<h2 class="anchored" data-anchor-id="conclusão">Conclusão</h2>
<p>Conclui-se que na regressão linear múltipla o aumento nas variáveis <strong><em>crim</em></strong> (taxa de criminalidade), <strong><em>nox</em></strong> (concentração de óxido de nitrogênio), <strong><em>dis</em></strong> (distância média ponderada dos cinco centros de emprego de Boston), <strong><em>tax</em></strong> (imposto sobre a propriedade), <strong><em>ptratio</em></strong> (relação de alunos / professor) e <strong><em>lstat</em></strong> (menor status da populaçao) <strong>implica em redução do valor mediano das habitações</strong>.</p>
<p>Por meio dos coeficientes padronizados, entre estas variáveis acima listadas, <strong><em>lstat</em></strong> (menor status da população) com coeficiente (-0.4057349) e <strong><em>dis</em></strong> (distância média ponderada dos cinco centros de emprego) com coeficiente (-0.3417617) <strong>são as que exercem as maiores influências negativas sobre o preço mediano das casas</strong>.</p>
<p>Em contrapartida, o aumento nas variáveis <strong><em>zn</em></strong> (proporção de terrenos residenciais acima de 25.000 sq.ft), <strong><em>chas</em></strong> (variável dummy, 1 se a área é limitada pelo rio e 0 caso contrário), <strong><em>rm</em></strong> (número médio de quartos por habitação), <strong><em>rad</em></strong> (índice de acessibilidade à radial highway) e <strong><em>black</em></strong> (1000(bk-0,63)<sup>2</sup>), onde bk é igual à oporção da população negra) <strong>resulta em maiores valores medianos das casas</strong>.</p>
<p>Por meio dos coeficientes padronizados, as variáveis <strong><em>rad</em></strong> (índice de acessibilidade à radial highway) com coeficiente (0.2836511) e <strong><em>rm</em></strong> (número médio de quartos) com coeficiente (0.2904234) <strong>exercem as maiores influências positivas sobre o preço mediano das casas</strong>.</p>

</section>


<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography"><h2 class="anchored quarto-appendix-heading">Referências</h2><div id="refs" class="references csl-bib-body hanging-indent" role="doc-bibliography">
<div id="ref-bommaeUnderstandingDiagnosticPlots2015" class="csl-entry" role="doc-biblioentry">
Bommae, King. 2015. <span>«Understanding <span>Diagnostic Plots</span> for <span>Linear Regression Analysis</span> | <span>University</span> of <span>Virginia Library Research Data Services</span> + <span>Sciences</span>»</span>. https://data.library.virginia.edu/diagnostic-plots/.
</div>
<div id="ref-lantzbrettMachineLearning2013" class="csl-entry" role="doc-biblioentry">
Lantz, Brett. 2013. <em>Machine <span>Learning</span> with <span>R</span></em>. First. <span>Birmingham, UK</span>.
</div>
<div id="ref-larsonronEstatisticaAplicada1941" class="csl-entry" role="doc-biblioentry">
Larson, Ron, e Betsy Farber. 1941. <em><span>Estatística Aplicada</span></em>. Second. <span>São Paulo</span>: <span>Prentice Hall</span>.
</div>
<div id="ref-morettinpedroalbertoEstatisticaCienciaDados2022" class="csl-entry" role="doc-biblioentry">
Morettin, Pedro Alberto, e Singer, Julio da Motta. 2022. <em><span>Estatística e Ciência de Dados</span></em>. First. <span>Rio de Janeiro</span>: <span>LTC - Livros Técnicos e Científicos Editora Ltda</span>.
</div>
<div id="ref-pianezzerguilhermeaugustoModelagemEstatistica2020" class="csl-entry" role="doc-biblioentry">
Pianezzer, Guilherme Augusto. 2020. <em><span>Modelagem Estatística</span></em>. First. Vol. 1. <span>Curitiba</span>: <span>Contentus</span>.
</div>
</div></section><section class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Notas de rodapé</h2>

<ol>
<li id="fn1" role="doc-endnote"><p>Simple linear regression defines the relationship between a dependent variable and a single independent predictor variable using a line denoted by an equation in the following form: y = a + bx (..) The intercept describes where the line crosses the y axis, while the slope describes the change in y given an increase of x.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2" role="doc-endnote"><p>This plot shows if residuals have non-linear patterns. There could be a non-linear relationship between predictor variables and an outcome variable and the pattern could show up in this plot if the model doesn’t capture the non-linear relationship. If you find equally spread residuals around a horizontal line without distinct patterns, that is a good indication you don’t have non-linear relationships.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copiada");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      let href = ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
</div> <!-- /content -->



</body></html>